### PR TITLE
Combinatorics

### PR DESCRIPTION
**Pull request by GeoffreyPS**
In response to Issue #13. 

Please let me know if you need anything added for this to be accepted.

### CODE REVIEW

**Comment by crertel** [comment]
@GeoffreyPS This looks great, and good work on the tests!

If you could, though, let's change `combinations` to `n_choose_k`, and also could you write a little blurb describing what `falling_factorial` does.

Otherwise, I think this is about ready to go!

**Comment by GeoffreyPS** [comment]
While this code fits what @crertel had requested, I would like to fix a few type annotations and include a rising_factorial function for completeness. I'll have those updates sent in early this week, possibly today.

As a side note (this might need to be a new issue): I am not able to run dialyzer on this code because of a conflict with `jsx`, a json library used as a dependency with `excoveralls`. The problem results from not being able to build the persistent lookup tree (see issues talentdeficit/jsx#103 and jeremyjh/dialyxir#56 ).  I believe the issue has been resolved and could get fixed in this use case by using excoveralls version `~0.6` instead of `~0.3`, which would include an updated version of `jsx` as a dependency. 

I have tried this fix locally on my machine and it appears to work, but I don't know if this has other consequences for the rest of the library in your development/ci/test setup.

**Comment by GeoffreyPS** [comment]
Ok. I think that finishes it up. Please let me know if the documentation is clear enough, or if there is anything else that should be resolved before merging.

**Comment by crertel** [comment]
Feel free to update the `jsx` dependency and coveralls, and if that passes CI I'll merge it.

**Comment by GeoffreyPS** [comment]
Looks like updating coveralls was all that was required to get the updated dependency on `jsx`. Thanks for letting me test that out.

**Comment by crertel** [comment]
Looks great man!

Merging.

**Pull request merged**
