### PR TITLE
10 add test data - closes #10

### LINKED ISSUE #10: Needs a test data set
We need a test data set so we can run integration tests on a realistic use case.

### PR DESCRIPTION
**Pull request by neerajt**

### CODE REVIEW

**Comment by neerajt** [comment]
@crertel:

Beware: The tests are deceiving, it's still not trying to compile `test/test_helper.ex` in `mix test`.

**Comment by crertel** [comment]
@neerajt so, I fixed the part where the helpers were ignored.

Basically, look at the changes I've made to the mixfile--we needed to nudge mix to compile the new `test/helpers` directory (where I relocated `test_helper.ex` to). I also updated the `statisaur_test.exs` file to also invoke the doctests for the helpers module.

I've made a minor tweak to the `pluck` test to make it pass, but I'm not sure I get where you were going with that and the rest of the `pluck` family. Lastly, the `parse_csv` stuff gets upset if it decides to load the columns in the wrong order.

We *might* want to either consider more stable loading of the CSVs, or perhaps even switching to maps where the column name is the key and the column data are the values.
Something like:

```
iex> %{"temperature": [55.0, 32.0, 110.0], "chirp_freq": [43,52,23]}
```

Thoughts?

**Comment by neerajt** [comment]
@crertel All tests passing now -- but I do like the format you proposed:

`%{"temperature": [55.0, 32.0, 110.0], "chirp_freq": [43,52,23]}`

I can work on changing things around to make that happen later today/tomorrow.

**Comment by crertel** [comment]
Awesome!

A more detailed CSV library parser would be useful later, but again this is just CSV-lite for use with our test suite. Would you mind elaborating on the docs for how the `pluck` functions are intended to be used? I'm not quite sure I understand.

**Comment by neerajt** [comment]
@crertel Made the changes we discussed. I think this is ready pending one last review from you.

**Comment by crertel** [comment]
Looks good to me. Merging.

**Review by crertel — COMMENTED** [review]
Looks good!

We talked about this in the PR comments.

**Pull request merged**
